# Generated by Django 4.0.1 on 2022-02-16 05:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sudarshoe.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('image', models.ImageField(null=True, upload_to='sudarshoe/', validators=[sudarshoe.models.validate_image])),
                ('price', models.BigIntegerField()),
                ('material', models.CharField(max_length=255)),
                ('weight', models.IntegerField()),
                ('size', models.CharField(max_length=255)),
                ('stock', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('trans_status', models.CharField(max_length=255)),
                ('payment_method', models.CharField(max_length=255)),
                ('pay_status', models.CharField(max_length=255)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='sudarshoe.product')),
            ],
        ),
    ]
